apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-epitrip-website-frontend-hpa
  namespace: prod-epitrip-website-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-epitrip-website-frontend-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
