name: tests_build_deploy_cluster_staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  tests_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js to specific version LTS and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies for project
        run: npm install

      - name: Lint TypeScript to App
        run: npm run lint:ts

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/staging/Dockerfile
          push: true
          tags: corentin35/epitrip-frontend:staging-${{ github.sha }}

      - name: Replace image tag in deployment.yaml for Kubernetes
        run: |
          sed -i 's/\${TAG_VERSION}/'${{ github.sha }}'/g' k8s/staging/deployment.yaml

      - name: Connect to the cluster K3S for deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            apply -f k8s/staging/namespace.yaml -f k8s/staging/certificate.yaml -f k8s/staging/docker-registry-secret.yaml -f k8s/staging/deployment.yaml -f k8s/staging/hpa.yaml -f k8s/staging/ingress.yaml -f k8s/staging/service.yaml
